#!/bin/bash
# make sure gas reports are checked in with this commit

git diff --color=always ${1:reports} | grep .

if [ $? == 1 ]; then
  #diff with no error - ok
  exit
else
  echo ERROR: found above unchecked reports. 
  exit 1
fi

